(() => {
  'use strict';
  const STORAGE_KEY='khairpur_admin_data_v1', PIN_KEY='khairpur_admin_pin_v1';
  const BANK_DETAILS={bank:'MCB Bank',title:'Tanveer Hussain',account:'1325688651006203'};
  const emptyData=()=>({version:1,orders:[],workers:[],logs:[],quotations:[],updatedAt:new Date().toISOString()});
  let data=load(), deleteTarget=null, cloudReady=false;
  const $=(selector,root=document)=>root.querySelector(selector), $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const uid=()=>crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,(c)=>{const r=Math.random()*16|0;return(c==='x'?r:(r&0x3|0x8)).toString(16)});
  const cleanPhone=(value)=>String(value||'').replace(/[^0-9]/g,'').replace(/^0/,'92');
  const esc=(value)=>String(value??'').replace(/[&<>"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
  const money=(value)=>`PKR ${new Intl.NumberFormat('en-PK',{maximumFractionDigits:0}).format(Number(value)||0)}`;
  const dateLabel=(value)=>value?new Intl.DateTimeFormat('en-PK',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`)):'Not set';
  function load(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!parsed||!Array.isArray(parsed.orders)||!Array.isArray(parsed.workers)||!Array.isArray(parsed.logs))return emptyData();if(!Array.isArray(parsed.quotations))parsed.quotations=[];return parsed}catch{return emptyData()}}
  function save(){data.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));renderAll()}
  function log(action,detail){const item={id:uid(),action,detail,at:new Date().toISOString()};data.logs.unshift(item);data.logs=data.logs.slice(0,500);if(cloudReady)window.KhairpurCloud.addLog(item).catch(()=>{})}
  const cloudCall=async(promise,label)=>{try{const result=await promise;if(result?.error)throw result.error;return result}catch(error){alert(`${label} cloud sync failed. Local copy is saved. ${error.message||''}`);return null}};
  const toHex=(bytes)=>[...bytes].map((byte)=>byte.toString(16).padStart(2,'0')).join('');
  const fromHex=(value)=>new Uint8Array(value.match(/.{1,2}/g).map((byte)=>parseInt(byte,16)));
  async function hash(value,saltHex){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(value),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:fromHex(saltHex),iterations:150000},material,256);return toHex(new Uint8Array(bits))}
  async function makePinRecord(value){const salt=crypto.getRandomValues(new Uint8Array(16));const saltHex=toHex(salt);return JSON.stringify({salt:saltHex,hash:await hash(value,saltHex),iterations:150000})}

  const accessScreen=$('#access-screen'),app=$('#admin-app'),accessCopy=$('#access-copy'),accessForm=$('#access-form'),accessPin=$('#access-pin'),accessStatus=$('#access-status');
  const hasPin=()=>Boolean(localStorage.getItem(PIN_KEY));
  function showAdmin(){sessionStorage.setItem('khairpur_admin_unlocked','1');$('#invite-screen').hidden=true;accessScreen.hidden=true;app.hidden=false;renderAll()}
  function lockAdmin(){sessionStorage.removeItem('khairpur_admin_unlocked');$('#invite-screen').hidden=true;app.hidden=true;accessScreen.hidden=false;accessPin.value='';accessCopy.textContent='Enter the device PIN to open private business records.';accessPin.focus()}
  if(hasPin())accessCopy.textContent='Enter the device PIN to open private business records.';
  if(hasPin()&&sessionStorage.getItem('khairpur_admin_unlocked')==='1')showAdmin();
  accessForm.addEventListener('submit',async(event)=>{event.preventDefault();const pin=accessPin.value.trim();if(!/^\d{6,12}$/.test(pin)){accessStatus.textContent='Use a 6–12 digit PIN.';return}if(!hasPin()){localStorage.setItem(PIN_KEY,await makePinRecord(pin));log('Security','Device PIN created');save();showAdmin();return}try{const record=JSON.parse(localStorage.getItem(PIN_KEY));const digest=await hash(pin,record.salt);if(digest===record.hash){accessStatus.textContent='';showAdmin()}else accessStatus.textContent='Incorrect PIN.'}catch{accessStatus.textContent='PIN record is damaged. Restore browser data or reset this workspace.'}});
  $('#lock-admin').addEventListener('click',lockAdmin);

  const inviteScreen=$('#invite-screen'),inviteEmail=$('#invite-email'),inviteForm=$('#invite-form'),invitePassword=$('#invite-password'),invitePasswordConfirm=$('#invite-password-confirm'),inviteStatus=$('#invite-status');
  function showInviteScreen(session){accessScreen.hidden=true;app.hidden=true;inviteScreen.hidden=false;inviteEmail.textContent=session?.user?.email||'your account';history.replaceState(null,'',location.pathname+location.search)}
  const isInviteOrRecoveryLink=window.KHAIRPUR_AUTH_HASH_TYPE==='invite'||window.KHAIRPUR_AUTH_HASH_TYPE==='recovery';
  if(window.KhairpurCloud){
    window.KhairpurCloud.client.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'||(event==='SIGNED_IN'&&isInviteOrRecoveryLink))showInviteScreen(session)});
  }
  inviteForm?.addEventListener('submit',async(event)=>{
    event.preventDefault();
    if(invitePassword.value.length<8){inviteStatus.textContent='Password must be at least 8 characters.';return}
    if(invitePassword.value!==invitePasswordConfirm.value){inviteStatus.textContent='Passwords do not match.';return}
    inviteStatus.textContent='Saving password…';
    const{error}=await window.KhairpurCloud.client.auth.updateUser({password:invitePassword.value});
    if(error){inviteStatus.textContent=`Could not set password: ${error.message}`;return}
    inviteStatus.textContent='Password set. You can now sign in from Backup & Settings → Admin cloud login.';
    setTimeout(()=>{inviteScreen.hidden=true;accessScreen.hidden=false},2000);
  });

  const titles={dashboard:'Business overview',orders:'Orders & leads',quotes:'Quotes & invoices',calculator:'Quick calculator',workers:'Worker directory',media:'Pictures & videos',logs:'Activity history',settings:'Backup & settings'};
  function switchView(name){$$('.nav-item').forEach((item)=>item.classList.toggle('active',item.dataset.view===name));$$('.admin-view').forEach((panel)=>panel.classList.toggle('active',panel.dataset.viewPanel===name));$('#view-title').textContent=titles[name];$('.sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'})}
  $$('.nav-item').forEach((button)=>button.addEventListener('click',()=>switchView(button.dataset.view)));
  $$('[data-view-link]').forEach((button)=>button.addEventListener('click',()=>switchView(button.dataset.viewLink)));
  $('.sidebar-toggle').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
  $('#today').textContent=new Intl.DateTimeFormat('en-PK',{weekday:'long',day:'numeric',month:'long'}).format(new Date());

  function updateSyncStatus(){const el=$('#sync-status');if(!el)return;if(cloudReady){el.className='sync-status sync-cloud';el.innerHTML='<i></i> <span>Cloud connected — syncs everywhere</span>'}else{el.className='sync-status sync-local';el.innerHTML='<i></i> <span>Local only — tap to sync</span>'}}
  $('#sync-status').addEventListener('click',()=>{if(cloudReady)return;switchView('settings');const email=$('#cloud-auth-form')?.elements?.email;if(email)email.focus()});
  updateSyncStatus();

  const orderDialog=$('#order-dialog'),orderForm=$('#order-form'),workerDialog=$('#worker-dialog'),workerForm=$('#worker-form'),mediaDialog=$('#media-dialog'),mediaForm=$('#media-form'),confirmDialog=$('#confirm-dialog'),quoteDialog=$('#quote-dialog'),quoteForm=$('#quote-form'),quoteItemsBody=$('#quote-items-body');
  const resetForm=(form)=>{form.reset();form.elements.id.value=''};
  function openOrder(id){resetForm(orderForm);$('#order-dialog-title').textContent=id?'Edit order or lead':'Add order or lead';if(id){const record=data.orders.find((item)=>item.id===id);if(!record)return;Object.entries(record).forEach(([key,value])=>{if(orderForm.elements[key])orderForm.elements[key].value=value??''})}orderDialog.showModal()}
  function openWorker(id){resetForm(workerForm);$('#worker-dialog-title').textContent=id?'Edit worker':'Add worker';if(id){const record=data.workers.find((item)=>item.id===id);if(!record)return;Object.entries(record).forEach(([key,value])=>{if(workerForm.elements[key])workerForm.elements[key].value=value??''})}workerDialog.showModal()}
  $$('[data-open-order]').forEach((button)=>button.addEventListener('click',()=>openOrder()));
  $$('[data-open-worker]').forEach((button)=>button.addEventListener('click',()=>openWorker()));
  $$('[data-open-media]').forEach((button)=>button.addEventListener('click',()=>{mediaForm.reset();$('#upload-status').textContent='';$('#media-local-warning').hidden=cloudReady;mediaDialog.showModal()}));
  orderForm.addEventListener('submit',async(event)=>{event.preventDefault();if(event.submitter?.value==='cancel'){orderDialog.close();return}if(!orderForm.reportValidity())return;const values=Object.fromEntries(new FormData(orderForm)),now=new Date().toISOString();let record;if(values.id){const index=data.orders.findIndex(item=>item.id===values.id);record=data.orders[index]={...data.orders[index],...values,amount:Number(values.amount)||0,updatedAt:now};log('Order updated',`${values.customer} — ${values.product}`)}else{values.id=uid();values.amount=Number(values.amount)||0;values.createdAt=now;values.updatedAt=now;record=values;data.orders.unshift(record);log('Order added',`${values.customer} — ${values.product}`)}save();if(cloudReady)await cloudCall(KhairpurCloud.saveOrder(record),'Order');orderDialog.close()});
  workerForm.addEventListener('submit',async(event)=>{event.preventDefault();if(event.submitter?.value==='cancel'){workerDialog.close();return}if(!workerForm.reportValidity())return;const values=Object.fromEntries(new FormData(workerForm)),now=new Date().toISOString();let record;if(values.id){const index=data.workers.findIndex(item=>item.id===values.id);record=data.workers[index]={...data.workers[index],...values,updatedAt:now};log('Worker updated',`${values.name} — ${values.role}`)}else{values.id=uid();values.createdAt=now;values.updatedAt=now;record=values;data.workers.unshift(record);log('Worker added',`${values.name} — ${values.role}`)}save();if(cloudReady)await cloudCall(KhairpurCloud.saveWorker(record),'Worker');workerDialog.close()});
  mediaForm.addEventListener('submit',async(event)=>{event.preventDefault();if(event.submitter?.value==='cancel'){mediaDialog.close();return}if(!mediaForm.reportValidity())return;const file=mediaForm.elements.file.files[0],status=$('#upload-status'),allowed=['image/jpeg','image/png','image/webp','video/mp4','video/webm'];if(!file||!allowed.includes(file.type)){status.textContent='Please select a supported JPG, PNG, WebP, MP4 or WebM file.';return}const type=file.type.startsWith('video/')?'video':'image',limit=type==='video'?100*1024*1024:12*1024*1024;if(file.size>limit){status.textContent=`${type==='video'?'Video':'Image'} is too large. Maximum ${type==='video'?'100 MB':'12 MB'}.`;return}status.textContent='Saving media…';const record={id:uid(),title:mediaForm.elements.title.value.trim(),category:mediaForm.elements.category.value,description:mediaForm.elements.description.value.trim(),published:mediaForm.elements.published.checked,type,mime:file.type,size:file.size,filename:file.name,createdAt:new Date().toISOString()};try{if(cloudReady){await KhairpurCloud.uploadMedia(record,file)}else{record.blobData=await file.arrayBuffer();await MediaDB.put(record)}log('Media uploaded',`${record.title} — ${record.published?'Published':'Draft'}`);save();await renderMedia();mediaDialog.close()}catch(error){status.textContent=`Upload failed: ${error.message||'Please try again.'}`}});
  function requestDelete(type,id,label,record=null){deleteTarget={type,id,label,record};confirmDialog.showModal()}
  confirmDialog.addEventListener('close',async()=>{if(confirmDialog.returnValue!=='confirm'||!deleteTarget)return;if(deleteTarget.type==='media'){if(cloudReady)await cloudCall(KhairpurCloud.deleteMedia(deleteTarget.record),'Media');else await MediaDB.remove(deleteTarget.id);log('Media deleted',deleteTarget.label);deleteTarget=null;save();await renderMedia();return}if(deleteTarget.type==='quote'){data.quotations=data.quotations.filter(item=>item.id!==deleteTarget.id);log('Quotation deleted',deleteTarget.label);deleteTarget=null;save();return}const list=deleteTarget.type==='order'?'orders':'workers',id=deleteTarget.id,type=deleteTarget.type;data[list]=data[list].filter(item=>item.id!==id);if(cloudReady)await cloudCall(type==='order'?KhairpurCloud.deleteOrder(id):KhairpurCloud.deleteWorker(id),type==='order'?'Order':'Worker');log(`${type==='order'?'Order':'Worker'} deleted`,deleteTarget.label);deleteTarget=null;save()});

  function statusClass(status){return status.toLowerCase().replaceAll(' ','-')}
  function filteredOrders(){const query=$('#order-search').value.toLowerCase().trim(),filter=$('#order-filter').value;return data.orders.filter((item)=>(filter==='all'||item.status===filter)&&[item.customer,item.phone,item.city,item.product,item.type].join(' ').toLowerCase().includes(query))}
  function renderOrders(){const records=filteredOrders(),body=$('#orders-body');body.innerHTML=records.map((item)=>`<tr><td><strong>${esc(item.customer)}</strong><small><a href="https://wa.me/${cleanPhone(item.phone)}" target="_blank" rel="noopener">${esc(item.phone)}</a> • ${esc(item.city||'No city')}</small></td><td><strong>${esc(item.product)}</strong><small>${esc(item.type)}${item.quantity?` • ${esc(item.quantity)}`:''}</small></td><td><span class="status ${statusClass(item.status)}">${esc(item.status)}</span></td><td>${esc(dateLabel(item.followup))}</td><td>${esc(money(item.amount))}</td><td><div class="row-actions"><button class="icon-action" data-edit-order="${item.id}" aria-label="Edit ${esc(item.customer)}">✎</button><button class="icon-action danger" data-delete-order="${item.id}" aria-label="Delete ${esc(item.customer)}">×</button></div></td></tr>`).join('');$('#orders-empty').hidden=records.length>0;$$('[data-edit-order]',body).forEach((button)=>button.onclick=()=>openOrder(button.dataset.editOrder));$$('[data-delete-order]',body).forEach((button)=>button.onclick=()=>{const item=data.orders.find((row)=>row.id===button.dataset.deleteOrder);requestDelete('order',item.id,`${item.customer} — ${item.product}`)})}
  $('#order-search').addEventListener('input',renderOrders);$('#order-filter').addEventListener('change',renderOrders);
  function filteredWorkers(){const query=$('#worker-search').value.toLowerCase().trim(),filter=$('#worker-filter').value;return data.workers.filter((item)=>(filter==='all'||item.status===filter)&&[item.name,item.phone,item.role,item.area].join(' ').toLowerCase().includes(query))}
  function renderWorkers(){const records=filteredWorkers(),grid=$('#worker-grid');grid.innerHTML=records.map((item)=>`<article class="worker-card"><header><span class="worker-avatar">${esc(item.name.charAt(0).toUpperCase())}</span><span class="status ${statusClass(item.status)}">${esc(item.status)}</span></header><h2>${esc(item.name)}</h2><span class="role">${esc(item.role)}</span><div class="worker-details"><a href="tel:${cleanPhone(item.phone)}">☎ ${esc(item.phone)}</a><span>Area: ${esc(item.area||'Not recorded')}</span><span>Emergency: ${esc(item.emergency||'Not recorded')}</span><span>Joined: ${esc(dateLabel(item.joined))}</span></div><footer><button data-edit-worker="${item.id}">Edit details</button><button class="danger-text" data-delete-worker="${item.id}">Remove</button></footer></article>`).join('');$('#workers-empty').hidden=records.length>0;$$('[data-edit-worker]',grid).forEach((button)=>button.onclick=()=>openWorker(button.dataset.editWorker));$$('[data-delete-worker]',grid).forEach((button)=>button.onclick=()=>{const item=data.workers.find((row)=>row.id===button.dataset.deleteWorker);requestDelete('worker',item.id,`${item.name} — ${item.role}`)})}
  $('#worker-search').addEventListener('input',renderWorkers);$('#worker-filter').addEventListener('change',renderWorkers);
  let mediaUrls=[];
  async function renderMedia(){mediaUrls.forEach(url=>URL.revokeObjectURL(url));mediaUrls=[];const query=$('#media-search').value.toLowerCase().trim(),filter=$('#media-filter').value,raw=cloudReady?await KhairpurCloud.allMedia():await MediaDB.all(),all=raw.map(item=>cloudReady?{...item,type:item.media_type,size:item.size_bytes,src:item.public_url,createdAt:item.created_at}:item).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),records=all.filter(item=>[item.title,item.category,item.description].join(' ').toLowerCase().includes(query)&&(filter==='all'||filter===item.type||(filter==='published'&&item.published)||(filter==='draft'&&!item.published))),grid=$('#admin-media-grid');grid.innerHTML=records.map(item=>{const src=cloudReady?item.src:URL.createObjectURL(item.blobData?new Blob([item.blobData],{type:item.mime}):item.blob);if(!cloudReady)mediaUrls.push(src);return `<article class="admin-media-card"><div class="admin-media-preview">${item.type==='video'?`<video src="${src}" controls preload="metadata"></video>`:`<img src="${src}" alt="${esc(item.title)}">`}<span class="media-type">${esc(item.type)}</span></div><div class="admin-media-copy"><h3>${esc(item.title)}</h3><p>${esc(item.category)} • ${(item.size/1024/1024).toFixed(1)} MB</p><footer><span class="status ${item.published?'media-published':'media-draft'}">${item.published?'Published':'Draft'}</span><div><button data-toggle-media="${item.id}">${item.published?'Unpublish':'Publish'}</button><button data-delete-media="${item.id}">Delete</button></div></footer></div></article>`}).join('');$('#media-empty').hidden=records.length>0;$$('[data-toggle-media]',grid).forEach(button=>button.onclick=async()=>{const item=all.find(record=>record.id===button.dataset.toggleMedia);item.published=!item.published;if(cloudReady)await cloudCall(KhairpurCloud.setMediaPublished(item.id,item.published),'Media status');else await MediaDB.put(item);log('Media status changed',`${item.title} — ${item.published?'Published':'Draft'}`);save();renderMedia()});$$('[data-delete-media]',grid).forEach(button=>button.onclick=()=>{const item=all.find(record=>record.id===button.dataset.deleteMedia);requestDelete('media',item.id,item.title,item)})}
  $('#media-search').addEventListener('input',renderMedia);$('#media-filter').addEventListener('change',renderMedia);
  function logMarkup(items){return items.map((item)=>`<div class="activity-item"><strong>${esc(item.action)} — ${esc(item.detail)}</strong><span>${new Intl.DateTimeFormat('en-PK',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.at))}</span></div>`).join('')}
  function renderLogs(){$('#recent-logs').innerHTML=data.logs.length?logMarkup(data.logs.slice(0,5)):'No activity recorded.';$('#recent-logs').classList.toggle('empty-state',!data.logs.length);$('#all-logs').innerHTML=logMarkup(data.logs);$('#logs-empty').hidden=data.logs.length>0}
  function renderDashboard(){const active=data.orders.filter((item)=>!['Completed','Lost'].includes(item.status)),today=new Date().toISOString().slice(0,10),due=active.filter((item)=>item.followup&&item.followup<=today);$('#metric-open').textContent=active.length;$('#metric-followups').textContent=due.length;$('#metric-value').textContent=money(data.orders.filter((item)=>['Confirmed','In progress','Delivered'].includes(item.status)).reduce((sum,item)=>sum+(Number(item.amount)||0),0));$('#metric-workers').textContent=data.workers.filter((item)=>item.status==='Active').length;$('#followup-list').innerHTML=due.length?due.sort((a,b)=>a.followup.localeCompare(b.followup)).slice(0,6).map((item)=>`<div class="record-row"><div><strong>${esc(item.customer)} — ${esc(item.product)}</strong><small>${esc(item.phone)} • ${esc(item.city||'No city')}</small></div><time>${esc(dateLabel(item.followup))}</time></div>`).join(''):'No follow-ups due.';$('#followup-list').classList.toggle('empty-state',!due.length)}
  function renderAll(){renderOrders();renderWorkers();renderLogs();renderDashboard();renderMedia();renderQuotes()}

  function nextDocNumber(type){const year=new Date().getFullYear(),prefix=type==='Invoice'?'INV':'Q',pattern=new RegExp(`^${prefix}-${year}-(\\d+)$`);const max=data.quotations.reduce((top,item)=>{const match=pattern.exec(item.number||'');return match?Math.max(top,Number(match[1])):top},0);return `${prefix}-${year}-${String(max+1).padStart(3,'0')}`}
  function makeItemRow(item={description:'',qty:1,rate:0}){const row=document.createElement('div');row.className='quote-item-row';row.innerHTML=`<input class="qi-desc" placeholder="e.g. Aseel palm, 6 ft" value="${esc(item.description)}"><input class="qi-qty" type="number" min="0" step="1" value="${item.qty}"><input class="qi-rate" type="number" min="0" step="1" value="${item.rate}"><span class="quote-item-amount">${money(0)}</span><button type="button" class="quote-item-remove" aria-label="Remove item">×</button>`;const qty=row.querySelector('.qi-qty'),rate=row.querySelector('.qi-rate'),amountEl=row.querySelector('.quote-item-amount');const recalcRow=()=>{amountEl.textContent=money((Number(qty.value)||0)*(Number(rate.value)||0));computeTotals()};qty.addEventListener('input',recalcRow);rate.addEventListener('input',recalcRow);row.querySelector('.qi-desc').addEventListener('input',computeTotals);row.querySelector('.quote-item-remove').addEventListener('click',()=>{row.remove();computeTotals()});recalcRow();return row}
  function collectItems(){return $$('.quote-item-row',quoteItemsBody).map((row)=>{const description=row.querySelector('.qi-desc').value.trim(),qty=Number(row.querySelector('.qi-qty').value)||0,rate=Number(row.querySelector('.qi-rate').value)||0;return {description,qty,rate,amount:qty*rate}}).filter((item)=>item.description||item.qty||item.rate)}
  function computeTotals(){const items=collectItems(),subtotal=items.reduce((sum,item)=>sum+item.amount,0),delivery=Number(quoteForm.elements.delivery.value)||0,installation=Number(quoteForm.elements.installation.value)||0,discount=Number(quoteForm.elements.discount.value)||0,grandTotal=Math.max(0,subtotal+delivery+installation-discount);$('#quote-totals').innerHTML=`<div><span>Items subtotal</span><strong>${money(subtotal)}</strong></div><div><span>Delivery + installation</span><strong>${money(delivery+installation)}</strong></div><div><span>Discount</span><strong>− ${money(discount)}</strong></div><div class="grand"><span>Grand total</span><strong>${money(grandTotal)}</strong></div>`;return {items,subtotal,delivery,installation,discount,grandTotal}}
  function openQuote(id){quoteForm.reset();quoteItemsBody.innerHTML='';$('#quote-dialog-title').textContent=id?'Edit document':'New quotation';if(id){const record=data.quotations.find((item)=>item.id===id);if(!record)return;Object.entries(record).forEach(([key,value])=>{if(quoteForm.elements[key])quoteForm.elements[key].value=value??''});(record.items||[]).forEach((item)=>quoteItemsBody.appendChild(makeItemRow(item)))}else{quoteForm.elements.date.value=new Date().toISOString().slice(0,10);quoteItemsBody.appendChild(makeItemRow())}computeTotals();quoteDialog.showModal()}
  $$('[data-open-quote]').forEach((button)=>button.addEventListener('click',()=>openQuote()));
  $('#quote-add-item').addEventListener('click',()=>{quoteItemsBody.appendChild(makeItemRow());computeTotals()});
  ['delivery','installation','discount'].forEach((name)=>quoteForm.elements[name].addEventListener('input',computeTotals));
  quoteForm.addEventListener('submit',(event)=>{event.preventDefault();if(event.submitter?.value==='cancel'){quoteDialog.close();return}if(!quoteForm.reportValidity())return;const totals=computeTotals();if(!totals.items.length){alert('Add at least one line item.');return}const values=Object.fromEntries(new FormData(quoteForm)),now=new Date().toISOString();let record;if(values.id){const index=data.quotations.findIndex((item)=>item.id===values.id);record=data.quotations[index]={...data.quotations[index],...values,items:totals.items,subtotal:totals.subtotal,delivery:totals.delivery,installation:totals.installation,discount:totals.discount,total:totals.grandTotal,updatedAt:now};log('Document updated',`${record.number} — ${values.customer}`)}else{values.id=uid();values.number=nextDocNumber(values.type);values.items=totals.items;values.subtotal=totals.subtotal;values.delivery=totals.delivery;values.installation=totals.installation;values.discount=totals.discount;values.total=totals.grandTotal;values.createdAt=now;values.updatedAt=now;record=values;data.quotations.unshift(record);log('Document created',`${record.number} — ${values.customer}`)}save();quoteDialog.close()});

  function printQuoteDoc(record){const itemsRows=record.items.map((item)=>`<tr><td>${esc(item.description)}</td><td>${item.qty}</td><td>${money(item.rate)}</td><td>${money(item.amount)}</td></tr>`).join(''),extras=(Number(record.delivery)||0)+(Number(record.installation)||0),balance=Math.max(0,(Number(record.total)||0)-(Number(record.paidAmount)||0));$('#quote-print').innerHTML=`<div class="print-header"><div class="print-brand"><img src="assets/khairpur-logo.jpg" alt=""><div><strong>Khairpur Date Palm & Nursery</strong><span>Khairpur Mirs, Sindh · 0302 3111589</span></div></div><div class="print-doc-type"><strong>${esc(record.type)}</strong><span>${esc(record.number)}</span></div></div><div class="print-meta"><div><strong>Bill to</strong><br>${esc(record.customer)}<br>${esc(record.phone)}${record.city?`<br>${esc(record.city)}`:''}</div><div style="text-align:right"><strong>Date</strong><br>${esc(dateLabel(record.date))}${record.validity?`<br><strong>${record.type==='Invoice'?'Due':'Valid until'}</strong><br>${esc(dateLabel(record.validity))}`:''}</div></div><table><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${itemsRows}</tbody></table><div class="print-totals"><div><span>Subtotal</span><strong>${money(record.subtotal)}</strong></div><div><span>Delivery + installation</span><strong>${money(extras)}</strong></div><div><span>Discount</span><strong>− ${money(record.discount)}</strong></div><div class="grand"><span>Grand total</span><strong>${money(record.total)}</strong></div>${record.paymentStatus&&record.paymentStatus!=='Not applicable'?`<div><span>Payment status</span><strong>${esc(record.paymentStatus)}</strong></div><div><span>Paid</span><strong>${money(record.paidAmount)}</strong></div><div><span>Balance due</span><strong>${money(balance)}</strong></div>`:''}</div>${record.notes?`<div class="print-notes"><strong>Notes:</strong> ${esc(record.notes)}</div>`:''}<div class="print-notes"><strong>Bank details for payment:</strong> ${esc(BANK_DETAILS.bank)} · Account title: ${esc(BANK_DETAILS.title)} · Account number: ${esc(BANK_DETAILS.account)}</div><div class="print-footer">Thank you for choosing Khairpur Date Palm & Nursery · kanhar4u@yahoo.com</div>`;setTimeout(()=>window.print(),80)}
  function whatsappQuoteShare(record){const lines=record.items.map((item)=>`• ${item.description} — ${item.qty} x ${money(item.rate)} = ${money(item.amount)}`).join('\n'),extras=(Number(record.delivery)||0)+(Number(record.installation)||0),text=`${record.type} ${record.number}\nKhairpur Date Palm & Nursery\n\nCustomer: ${record.customer}\n\n${lines}\n\nSubtotal: ${money(record.subtotal)}\nDelivery + Installation: ${money(extras)}\nDiscount: ${money(record.discount)}\nGrand Total: ${money(record.total)}${record.notes?`\n\nNotes: ${record.notes}`:''}\n\nBank details for payment:\n${BANK_DETAILS.bank}\nAccount title: ${BANK_DETAILS.title}\nAccount number: ${BANK_DETAILS.account}`;window.open(`https://wa.me/${cleanPhone(record.phone)}?text=${encodeURIComponent(text)}`,'_blank','noopener')}
  function filteredQuotes(){const query=$('#quote-search').value.toLowerCase().trim(),filter=$('#quote-filter').value;return data.quotations.filter((item)=>(filter==='all'||item.type===filter)&&[item.number,item.customer,item.phone].join(' ').toLowerCase().includes(query))}
  function renderQuotes(){const records=filteredQuotes(),body=$('#quotes-body');body.innerHTML=records.map((item)=>`<tr><td><strong>${esc(item.number)}</strong></td><td><strong>${esc(item.customer)}</strong><small>${esc(item.phone)}</small></td><td><span class="status ${item.type==='Invoice'?'confirmed':'quoted'}">${esc(item.type)}</span></td><td>${money(item.total)}</td><td>${esc(dateLabel(item.date))}</td><td><div class="row-actions"><button class="icon-action" data-print-quote="${item.id}" aria-label="Print ${esc(item.number)}">⎙</button><button class="icon-action" data-whatsapp-quote="${item.id}" aria-label="Share ${esc(item.number)} on WhatsApp">↗</button><button class="icon-action" data-edit-quote="${item.id}" aria-label="Edit ${esc(item.number)}">✎</button><button class="icon-action danger" data-delete-quote="${item.id}" aria-label="Delete ${esc(item.number)}">×</button></div></td></tr>`).join('');$('#quotes-empty').hidden=records.length>0;$$('[data-edit-quote]',body).forEach((button)=>button.onclick=()=>openQuote(button.dataset.editQuote));$$('[data-delete-quote]',body).forEach((button)=>button.onclick=()=>{const item=data.quotations.find((row)=>row.id===button.dataset.deleteQuote);requestDelete('quote',item.id,`${item.number} — ${item.customer}`)});$$('[data-print-quote]',body).forEach((button)=>button.onclick=()=>{const item=data.quotations.find((row)=>row.id===button.dataset.printQuote);printQuoteDoc(item)});$$('[data-whatsapp-quote]',body).forEach((button)=>button.onclick=()=>{const item=data.quotations.find((row)=>row.id===button.dataset.whatsappQuote);whatsappQuoteShare(item)})}
  $('#quote-search').addEventListener('input',renderQuotes);$('#quote-filter').addEventListener('change',renderQuotes);

  const calcInputs=['calc-rate','calc-qty','calc-delivery','calc-installation','calc-discount'].map((id)=>$(`#${id}`));
  function calcTotals(){const rate=Number($('#calc-rate').value)||0,qty=Number($('#calc-qty').value)||0,delivery=Number($('#calc-delivery').value)||0,installation=Number($('#calc-installation').value)||0,discount=Number($('#calc-discount').value)||0,subtotal=rate*qty,extras=delivery+installation,total=Math.max(0,subtotal+extras-discount);$('#calc-subtotal').textContent=money(subtotal);$('#calc-extras').textContent=money(extras);$('#calc-discount-out').textContent=`− ${money(discount)}`;$('#calc-total').textContent=money(total);return {rate,qty,delivery,installation,discount,subtotal,extras,total}}
  calcInputs.forEach((input)=>input.addEventListener('input',calcTotals));
  $('#calc-reset').addEventListener('click',()=>{calcInputs.forEach((input)=>input.value='');calcTotals()});
  $('#calc-whatsapp').addEventListener('click',()=>{const t=calcTotals(),text=`Khairpur Date Palm & Nursery — Quick estimate\n\nRate: ${money(t.rate)} x ${t.qty}\nSubtotal: ${money(t.subtotal)}\nDelivery + Installation: ${money(t.extras)}\nDiscount: ${money(t.discount)}\n\nEstimated Total: ${money(t.total)}\n\n(This is an estimate — final quotation confirmed separately.)`;window.open(`https://wa.me/923023111589?text=${encodeURIComponent(text)}`,'_blank','noopener')});
  calcTotals();

  function download(name,content,type='application/json'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function csv(rows,columns){const quote=(value)=>`"${String(value??'').replaceAll('"','""')}"`;return [columns.map(([label])=>quote(label)).join(','),...rows.map((row)=>columns.map(([,key])=>quote(row[key])).join(','))].join('\n')}
  $('#export-backup').onclick=()=>{log('Backup exported',`${data.orders.length} orders, ${data.workers.length} workers`);save();download(`khairpur-admin-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2))};
  $('#export-orders').onclick=()=>{log('Orders CSV exported',`${data.orders.length} records`);save();download('khairpur-orders.csv',csv(data.orders,[['Customer','customer'],['Phone','phone'],['City','city'],['Type','type'],['Product','product'],['Quantity','quantity'],['Amount PKR','amount'],['Status','status'],['Follow-up','followup'],['Notes','notes']]),'text/csv;charset=utf-8')};
  $('#export-workers').onclick=()=>{log('Workers CSV exported',`${data.workers.length} records`);save();download('khairpur-workers.csv',csv(data.workers,[['Name','name'],['Phone','phone'],['Role','role'],['Area','area'],['Joined','joined'],['Status','status'],['Emergency','emergency'],['Notes','notes']]),'text/csv;charset=utf-8')};
  $('#import-backup').addEventListener('change',async(event)=>{const file=event.target.files[0];if(!file)return;try{const incoming=JSON.parse(await file.text());if(!incoming||!Array.isArray(incoming.orders)||!Array.isArray(incoming.workers)||!Array.isArray(incoming.logs))throw new Error('Invalid');data=incoming;log('Backup restored',file.name);save();alert('Backup restored successfully.')}catch{alert('This is not a valid Khairpur Admin backup.')}event.target.value=''});
  $('#change-pin').onclick=()=>{const next=prompt('Enter a new 6–12 digit device PIN:');if(!next)return;if(!/^\d{6,12}$/.test(next)){alert('PIN must contain 6–12 digits.');return}makePinRecord(next).then((record)=>{localStorage.setItem(PIN_KEY,record);log('Security','Device PIN changed');save();alert('Device PIN updated.')})};
  const cloudForm=$('#cloud-auth-form'),cloudStatus=$('#cloud-auth-status'),cloudSignout=$('#cloud-signout');
  const validUuid=(value)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
  async function syncCloud(){cloudStatus.textContent='Syncing local records to Supabase…';for(const item of data.orders){if(!validUuid(item.id))item.id=uid();const result=await window.KhairpurCloud.saveOrder(item);if(result.error)throw result.error}for(const item of data.workers){if(!validUuid(item.id))item.id=uid();const result=await window.KhairpurCloud.saveWorker(item);if(result.error)throw result.error}for(const item of data.logs){if(!validUuid(item.id))item.id=uid();const result=await window.KhairpurCloud.addLog(item);if(result.error)throw result.error}const remote=await window.KhairpurCloud.loadBusinessData();data.orders=remote.orders;data.workers=remote.workers;data.logs=remote.logs;cloudReady=true;save();cloudStatus.textContent='Cloud connected. Orders, workers, logs and media are syncing.';cloudForm.hidden=true;cloudSignout.hidden=false;updateSyncStatus();renderMedia()}
  async function refreshCloud(){if(!window.KhairpurCloud){cloudStatus.textContent='Supabase is not ready. Check the project URL, anon key, and internet connection.';return}const session=await window.KhairpurCloud.session();if(session){try{await syncCloud()}catch(error){cloudStatus.textContent=`Cloud sync error: ${error.message}`}}}
  cloudForm.addEventListener('submit',async(event)=>{event.preventDefault();if(!window.KhairpurCloud){cloudStatus.textContent='Supabase is not ready. Check the project URL, anon key, and internet connection.';return}cloudStatus.textContent='Signing in…';const values=Object.fromEntries(new FormData(cloudForm)),result=await window.KhairpurCloud.signIn(values.email,values.password);if(result.error){cloudStatus.textContent=result.error.message;return}cloudForm.reset();try{await syncCloud()}catch(error){cloudStatus.textContent=`Cloud sync error: ${error.message}`}});
  cloudSignout.addEventListener('click',async()=>{if(window.KhairpurCloud)await window.KhairpurCloud.signOut();cloudReady=false;cloudForm.hidden=false;cloudSignout.hidden=true;cloudStatus.textContent='Signed out. Local device records remain available.';updateSyncStatus();renderAll()});
  refreshCloud();
  $('#global-search').onclick=()=>{switchView('orders');$('#order-search').focus()};
})();
