export const business = {
  name: 'Khairpur Date Palm & Nursery',
  shortName: 'Khairpur Palms',
  phone: '0302 3111589',
  phoneIntl: '923023111589',
  email: 'kanhar4u@yahoo.com',
  location: 'Khairpur Mirs, Sindh, Pakistan',
  facebook: 'https://web.facebook.com/profile.php?id=100064172491227',
};

export const pages = [
  {
    slug: 'date-palms', eyebrow: 'Authentic Khairpur stock', title: 'Choose a palm with confidence.',
    description: 'Buy Aseel and Qarbala date palms from Khairpur, Sindh — 1 to 20 ft, with pricing, supply, delivery and professional installation.',
    intro: 'A date palm is a long-term asset, not a quick garden purchase — a well-chosen, well-planted palm can be part of a property for decades. We help buyers compare purpose, variety, height, logistics and installation requirements before selecting stock, so the decision is based on the actual site and goal rather than a single photo. Whether the plan is one statement tree for a home entrance or a full commercial orchard, the right starting point is the same: clear requirements, verified current stock, and a supplier based in the growing region itself.',
    cta: 'Check palm availability', purpose: 'Date palm availability', image: 'assets/khairpur-date-palm-hero.webp', imageAlt: 'Date palm orchard in the warm light of Khairpur',
    facts: [['Aseel', 'Available from approximately 1–20 ft'], ['Qarbala', 'Available from approximately 1–10 ft'], ['Service', 'Supply and installation'], ['Origin', 'Khairpur Mirs, Sindh']],
    pricing: [
      ['Nursery Plant', '1.5–2 ft', 'PKR 2,000'],
      ['Date Palm', '5–6 ft', 'PKR 5,000'],
      ['Date Palm', '8–10 ft', 'PKR 6,000'],
      ['Date Palm', '10–12 ft', 'PKR 6,500'],
      ['Date Palm', '12–14 ft', 'PKR 7,000'],
      ['Date Palm', '14–16 ft', 'PKR 7,500'],
      ['Big Root Date Palm', '5–18 ft', 'PKR 10,000–12,000'],
    ],
    sections: [
      ['Aseel Date Palm', 'Khairpur’s best-known commercial date variety and a strong choice for orchard, farmhouse and landscape enquiries. Available from approximately 1 ft to 20 ft, so the same variety can serve a young starter planting or a tall, immediate-impact specimen. Availability changes by height and season, and is confirmed directly before quotation.', ['Multiple height bands', 'Farm and farmhouse use', 'Installation enquiry available']],
      ['Qarbala Date Palm', 'A regional date-palm option available in several young-to-established sizes, from approximately 1 ft to 10 ft. Qarbala is a good fit for buyers who want a mix of varieties within one planting, or who specifically want this locally recognised type. Exact stock and specification are confirmed before quotation.', ['Approximately 1–10 ft', 'Garden and farm enquiries', 'Direct nursery confirmation']],
      ['Mature and Big Root Palms', 'Larger, established palms — including big-root specimens up to around 18 ft — require careful access assessment, lifting equipment, transportation planning and a prepared planting site. These are quoted as individual projects after reviewing site photographs, access and quantity, rather than from height alone.', ['Site-access review', 'Handling and delivery planning', 'Professional installation']],
    ],
  },
  {
    slug: 'aseel-date-palm', eyebrow: 'Khairpur’s signature variety', title: 'Aseel date palms, selected at the source.',
    description: 'Buy authentic Aseel date palm plants from Khairpur, Sindh — 1 to 20 ft, with nursery selection, delivery and professional installation.',
    intro: 'Aseel is Khairpur’s signature date palm variety and one of the most recognised names in Pakistan’s date-growing tradition. Grown and selected in the nurseries around Khairpur Mirs, Sindh, Aseel date palms are valued for their strong root development, dependable growth and long commercial history in the region. Buyers can enquire about plants from approximately 1 ft through 20 ft — from young nursery stock suited to home gardens, to tall, established specimens for orchards and large landscape projects — subject to current nursery availability.',
    cta: 'Enquire about Aseel', purpose: 'Aseel Date Palm', image: 'assets/khairpur-date-palm-hero.webp', imageAlt: 'Healthy date palms growing in a sunlit orchard',
    facts: [['Height range', 'Approximately 1–20 ft'], ['Best for', 'Farms, orchards and landscapes'], ['Quote basis', 'Height, quantity and destination'], ['Support', 'Supply and installation']],
    sections: [
      ['Who is it for?', 'Aseel suits a wide range of buyers: agricultural investors planting a commercial orchard, farmhouse owners wanting a statement entrance tree, landscape contractors working on residential or commercial projects, and government or institutional buyers planting avenues and public spaces. What connects them is a preference for a date palm with authentic Khairpur provenance rather than an unverified or mixed-origin plant.', ['Orchard enquiries', 'Statement landscape planting', 'Bulk and individual orders', 'Government and institutional planting']],
      ['What affects the quotation?', 'Palm height alone is not enough to price a Khairpur Aseel date palm. Quantity, root-ball size, vehicle access at both the nursery and the delivery site, distance travelled, and whether installation is required all materially affect the final cost. A palm supplied only (no planting) will differ in price from one that includes machinery-assisted lifting, transport and professional planting at destination.', ['Required quantity', 'Delivery city and access', 'Supply-only or installation', 'Root-ball and handling requirements']],
      ['Why Aseel from Khairpur specifically', 'Khairpur, Sindh is one of Pakistan’s most established date-growing regions, and the Aseel variety has been cultivated here across generations of local nurseries. Buying from the source means the plant has been raised in soil and climate conditions similar to where it will likely be replanted, which supports a smoother establishment period compared with palms sourced from unrelated growing regions.', ['Regional growing expertise', 'Climate-matched stock', 'Direct nursery relationship']],
      ['Before you order', 'Ask for current stock imagery and confirm exactly how the quoted height is measured (from soil level to crown, or to leaf tip). For mature or fruit-bearing plants, fruiting history, gender and age should be confirmed for the specific tree where relevant, since these vary between individual palms even within the same variety.', ['Current-stock confirmation', 'Specification confirmation', 'Site information']],
    ],
  },
  {
    slug: 'qarbala-date-palm', eyebrow: 'Regional palm selection', title: 'Qarbala palms for farms and gardens.',
    description: 'Qarbala date palm plants from Khairpur, 1 to 10 ft, for farms, gardens and landscape planting, with delivery and installation assessment.',
    intro: 'Qarbala is a distinctive regional date palm variety carried by the nursery alongside Aseel, giving buyers a second authentic option when planning a farm, garden or landscape project. Qarbala palms are listed from approximately 1 ft to 10 ft, covering young nursery stock through to more established plants. Current availability, exact size and condition are always confirmed directly with the nursery team before a final quotation is issued, since stock changes with the season.',
    cta: 'Enquire about Qarbala', purpose: 'Qarbala Date Palm', image: 'assets/khairpur-date-palm-hero.webp', imageAlt: 'Established date palm trees in an agricultural landscape',
    facts: [['Height range', 'Approximately 1–10 ft'], ['Availability', 'Confirmed before quotation'], ['Use cases', 'Farm and garden enquiries'], ['Support', 'Delivery and installation assessment']],
    sections: [
      ['What makes Qarbala different', 'Qarbala carries its own regional character and is sought after by buyers who want variety within a planting, or who specifically know the name from local growing communities. It is commonly chosen alongside Aseel where a project wants a mix of varieties rather than a single-type orchard or garden.', ['Regional authenticity', 'Complements Aseel plantings', 'Recognised local variety']],
      ['Choose by outcome', 'The right size depends on the objective. Smaller plants (1–3 ft) suit buyers who want young palms to establish over time at a lower initial cost. Mid-range plants (4–7 ft) are a common choice for farmhouse gardens wanting a visible plant sooner. Larger Qarbala stock (8–10 ft) suits farms and landscape projects wanting a more immediate visual result.', ['Young planting stock', 'Established garden palms', 'Project quantities']],
      ['Plan delivery early', 'Larger palms need appropriate vehicle access at both ends of the journey, safe unloading space, and a planting location prepared in advance so the plant is not left waiting in transit conditions longer than necessary.', ['Destination review', 'Access assessment', 'Installation scope']],
      ['Get a useful quotation', 'Send your city, required quantity, preferred height and intended use (farm, garden, commercial project) in the first WhatsApp message. This single step reduces back-and-forth and avoids inaccurate first estimates.', ['City', 'Quantity and height', 'Purpose and timeline']],
    ],
  },
  {
    slug: 'palm-supply-delivery', eyebrow: 'From nursery to destination', title: 'Palm supply and delivery, planned properly.',
    description: 'Date palm supply and delivery enquiries from Khairpur for homes, farms and commercial landscape projects across Pakistan.',
    intro: 'A reliable delivery plan starts with the correct palm specification, quantity, destination and site-access information—not a generic transport estimate.',
    cta: 'Request delivery assessment', purpose: 'Palm supply and delivery', image: 'assets/real-palm-installation.webp', imageAlt: 'Mature date palm being handled by the Khairpur field team', imageAuthentic: true,
    facts: [['Stock', 'Confirmed at enquiry stage'], ['Delivery quote', 'Based on size, quantity and city'], ['Collection', 'Roadside collection listed'], ['Origin', 'Khairpur Mirs']],
    sections: [
      ['Supply confirmation', 'Current stock, variety and height should be confirmed before transport is planned.', ['Current imagery', 'Variety and quantity', 'Height specification']],
      ['Transport planning', 'Palm size and root preparation influence the appropriate vehicle and handling process.', ['Route and distance', 'Loading requirements', 'Safe support and protection']],
      ['Destination readiness', 'Access, unloading area and planting preparation should be reviewed before dispatch.', ['Vehicle access', 'Unloading space', 'Prepared planting area']],
    ],
  },
  {
    slug: 'palm-installation', eyebrow: 'Verified field capability', title: 'Professional mature-palm installation.',
    description: 'Machinery-assisted date palm installation and relocation enquiries backed by authentic field-work evidence.',
    intro: 'The Facebook archive contains authentic evidence of machinery-assisted mature-palm positioning and installation. Every new site still requires its own assessment.',
    cta: 'Discuss an installation', purpose: 'Professional palm installation', image: 'assets/real-palm-installation.webp', imageAlt: 'Machinery-assisted mature date palm installation by the company field team', imageAuthentic: true,
    facts: [['Evidence', 'Authentic company field media'], ['Method', 'Project-specific assessment'], ['Suitable for', 'Mature and large palms'], ['Quote needs', 'Location, access, size and quantity']],
    sections: [
      ['Why assessment matters', 'Large palms cannot be quoted responsibly from height alone. Ground conditions, access and equipment requirements change the plan.', ['Site photographs', 'Access measurements', 'Palm size and quantity']],
      ['What the service covers', 'Final scope is confirmed in the quotation and may include handling, transportation, positioning and planting.', ['Lifting plan', 'Placement coordination', 'Planting scope']],
      ['After installation', 'Watering and establishment guidance should be agreed for the specific project. No survival guarantee is implied unless written into the quotation.', ['Initial care instructions', 'Clear responsibility split', 'Written terms']],
    ],
  },
  {
    slug: 'date-products', eyebrow: 'From Khairpur’s date country', title: 'Aseel dates in more useful forms.',
    description: 'Fresh Aseel dates, dry dates (chuhara), date paste, syrup and powder from Khairpur, Sindh — for retail, food-service and wholesale buyers.',
    intro: 'Khairpur is one of Pakistan’s best-known date-growing regions, and Aseel dates from this area carry a strong local reputation for flavour and quality. Beyond fresh fruit, the nursery’s public catalogue covers a full range of value-added date products — dry dates, date paste, syrup and powder — aimed at everyday households, food-service businesses and commercial buyers looking for a consistent supply of Khairpur-grown Aseel dates in the format that suits their use.',
    cta: 'Request product availability', purpose: 'Date products', image: 'assets/date-products-hero.webp', imageAlt: 'Aseel dates presented with date syrup, paste and powder',
    facts: [['Fresh fruit', 'Seasonal Aseel date enquiries'], ['Traditional', 'Dry dates / chuhara'], ['Ingredients', 'Date paste and syrup'], ['Format', 'Date powder enquiries']],
    sections: [
      ['Fresh Aseel Dates', 'Promoted as hand-picked, premium-quality Khairpur dates, fresh Aseel is a seasonal product tied to the local harvest window. It suits households buying for daily consumption as well as retailers stocking up during peak season. Availability, grade and packaging must always be confirmed for the current season before ordering, since fresh fruit supply naturally varies through the year.', ['Seasonal availability', 'Retail and bulk enquiry', 'Packaging confirmation']],
      ['Dry Dates / Chuhara', 'Dry dates, locally known as chuhara, are a traditional shelf-stable format that stores well beyond the fresh season. This makes them a practical choice for households wanting dates year-round, for gift packaging, and for wholesale buyers who need a product with a longer shelf life than fresh fruit.', ['Grade confirmation', 'Pack-size enquiry', 'Bulk quantity enquiry']],
      ['Date Paste, Syrup and Powder', 'These value-added formats are relevant to bakeries, juice and dessert producers, and any food business looking for a natural date-based sweetener instead of refined sugar. Date paste works well in bars and baked goods, syrup suits drinks and glazes, and powder is useful where a dry, easily-dosed ingredient is needed in production.', ['Food-business use cases', 'MOQ and pack size required', 'Shelf-life confirmation required']],
      ['Buying fresh vs. processed', 'Choosing between fresh dates, chuhara and processed formats mainly comes down to intended use and storage. Fresh Aseel suits immediate consumption and gifting during season; chuhara suits longer home storage; paste, syrup and powder suit buyers who need a stable ingredient for food production rather than a fruit to eat directly.', ['Personal and family use', 'Retail resale', 'Food manufacturing input']],
    ],
  },
  {
    slug: 'wholesale-export', eyebrow: 'Commercial enquiries', title: 'A clearer path for wholesale buyers.',
    description: 'Structured wholesale and export enquiries for Khairpur date products and seasonal Pakistani fruit shipments.',
    intro: 'Commercial buyers need product specification, volume, packaging, destination and documentation—not a generic retail message. This page captures those details first.',
    cta: 'Start wholesale enquiry', purpose: 'Wholesale or export enquiry', image: 'assets/date-export-hero.webp', imageAlt: 'Premium dates prepared in cartons and food-safe pouches for wholesale supply',
    facts: [['Products', 'Dates and value-added formats'], ['Buyer type', 'Retailers and food businesses'], ['Quote basis', 'Product, volume and destination'], ['Seasonal', 'Mango campaigns appear on Facebook']],
    sections: [
      ['For retailers', 'Request product type, grade, pack size and order quantity. Current availability is confirmed directly.', ['Retail packaging enquiry', 'Bulk carton enquiry', 'Destination details']],
      ['For food businesses', 'Date paste, syrup and powder may suit bakery or production use. Specifications and documentation require confirmation.', ['Required format', 'Monthly or one-off volume', 'Food-use requirements']],
      ['For export enquiries', 'Facebook has promoted international seasonal shipments, but destination coverage and export terms must be reconfirmed for every campaign.', ['Country and city', 'Required quantity', 'Timeline and documentation']],
    ],
  },
  {
    slug: 'projects', eyebrow: 'Evidence over claims', title: 'Real work from the field.',
    description: 'Verified project evidence from Khairpur Date Palm & Nursery, beginning with mature palm installation.',
    intro: 'Only projects supported by authentic company media belong here. Stock imagery and AI-generated scenes are not presented as completed work.',
    cta: 'Discuss your project', purpose: 'Project enquiry', image: 'assets/real-palm-installation.webp', imageAlt: 'Authentic machinery-assisted date palm installation project', imageAuthentic: true,
    facts: [['Verified category', 'Mature palm installation'], ['Evidence source', 'Company Facebook archive'], ['Media status', 'Authentic field photograph'], ['Expansion', 'More case studies require owner data']],
    sections: [
      ['Mature Palm Field Installation', 'Authentic media shows a large palm being positioned with machinery while the field team prepares the planting area.', ['Machinery-assisted handling', 'On-site crew', 'Prepared installation area']],
      ['What is not yet documented', 'The public post does not specify location, client, date, quantity, project challenge or follow-up result.', ['Location needed', 'Scope and timeline needed', 'Aftercare result needed']],
      ['Case-study standard', 'Future projects should include before, during and after imagery plus written scope, measurable outcome and customer permission.', ['Before/after set', 'Client-approved description', 'Related service and CTA']],
    ],
    gallery: [
      ['assets/real-palm-installation.webp', 'Mature palm installation', 'Machinery-assisted positioning and field planting', 720, 960],
      ['assets/facebook/mango-harvest.jpg', 'Seasonal harvest', 'Authentic farm handling from the Facebook archive', 206, 206],
      ['assets/facebook/mango-sorting.jpg', 'Farm sorting', 'Fruit selection during seasonal activity', 206, 206],
      ['assets/facebook/mango-packing.jpg', 'Packing activity', 'Fruit prepared for onward delivery', 206, 206],
      ['assets/facebook/product-range.jpg', 'Product communication', 'Public Facebook product-range artwork', 206, 206],
    ],
  },
  {
    slug: 'about', eyebrow: 'Rooted in Khairpur', title: 'Local knowledge. Direct responsibility.',
    description: 'Learn what is publicly verified about Khairpur Date Palm & Nursery and the standards guiding its website content.',
    intro: 'Khairpur Date Palm & Nursery operates from Khairpur Mirs and publicly positions itself around palm supply, installation and date-related products.',
    cta: 'Speak with the nursery', purpose: 'General business enquiry', image: 'assets/real-palm-installation.webp', imageAlt: 'Khairpur Date Palm and Nursery team carrying out a mature palm installation', imageAuthentic: true,
    facts: [['Community', 'Approximately 29K Facebook followers'], ['Category', 'Landscape company'], ['Hours', 'Always open on Facebook'], ['Collection', 'Roadside collection listed']],
    ceo: {
      name: 'Tanveer Hussain Kanhar',
      designation: 'Founder & CEO',
      credentials: 'MBA in Business, University of London — 15+ years in Pakistan’s date palm and nursery trade',
      image: 'assets/ceo-tanveer-hussain-kanhar.jpg',
      bio: 'Tanveer Hussain Kanhar is the Founder and CEO of Khairpur Date Palm & Nursery. He holds an MBA in Business from the University of London and has spent more than 15 years working directly in Pakistan’s date palm and nursery trade — from sourcing and cultivating authentic Aseel and Qarbala varieties in Khairpur, Sindh, to building the supply, delivery and installation services the business runs today. His approach pairs that international business training with hands-on, on-the-ground experience in one of Pakistan’s most established date-growing regions. Under his leadership, the nursery holds to a simple standard: never present a palm, a product or a claim that hasn’t been verified. Tanveer stays directly involved with the field team on selection and planting standards, and remains personally reachable for buyers who prefer to deal with the business owner directly.',
      quote: 'Every palm we send out carries our name with it. That’s why we’d rather tell a customer “not available” than send the wrong plant.',
    },
    sections: [
      ['What we can verify', 'The company publicly lists Khairpur Mirs, a direct mobile number, email, palm supply and installation.', ['Public contact details', 'Palm and date-product media', 'Authentic installation evidence']],
      ['What we will not invent', 'Years in business, team biographies, certifications and project totals will be published only after owner verification.', ['No fabricated statistics', 'No invented testimonials', 'No stock images labelled as projects']],
      ['A better digital standard', 'The website organizes scattered Facebook content into product, service, project and enquiry journeys designed to answer buyer questions.', ['Clear product paths', 'Evidence-backed trust', 'Structured WhatsApp leads']],
    ],
  },
  {
    slug: 'contact', eyebrow: 'Direct nursery contact', title: 'Start with the details that matter.',
    description: 'Contact Khairpur Date Palm & Nursery for plant, installation, date-product, wholesale and export enquiries.',
    intro: 'A complete first message helps the nursery respond faster and more accurately. Share product, quantity, city, preferred size or pack format and timeline.',
    cta: 'Open structured WhatsApp enquiry', purpose: 'General enquiry', image: 'assets/khairpur-date-palm-hero.webp', imageAlt: 'Khairpur date palm orchard at golden hour',
    facts: [['Mobile / WhatsApp', '0302 3111589'], ['Email', 'kanhar4u@yahoo.com'], ['Location', 'Khairpur Mirs, Pakistan'], ['Hours', 'Always open on Facebook']],
    sections: [
      ['Palm enquiry checklist', 'Include variety, required height, quantity, delivery city and whether installation is required.', ['Variety', 'Height and quantity', 'City and site access']],
      ['Date-product checklist', 'Include product format, retail or wholesale status, quantity, packaging requirement and destination.', ['Product and volume', 'Pack format', 'Destination and timing']],
      ['Response quality', 'Clear inputs reduce repeated questions and make the first quotation materially more useful.', ['One structured message', 'Faster qualification', 'Fewer surprises']],
    ],
  },
];
