export const business = {
  name: 'Khairpur Date Palm & Nursery',
  shortName: 'Khairpur Palms',
  phone: '0302 3111589',
  phoneIntl: '923023111589',
  email: 'kanhar4u@yahoo.com',
  location: 'Khairpur Mirs, Sindh, Pakistan',
  facebook: 'https://web.facebook.com/profile.php?id=100064172491227',
};

export const pages = [
  {
    slug: 'date-palms', eyebrow: 'Authentic Khairpur stock', title: 'Choose a palm with confidence.',
    description: 'Explore Aseel, Qarbala and mature date palms supplied from Khairpur for homes, farms and landscape projects.',
    intro: 'Date palms are long-term assets. We help buyers compare purpose, height, logistics and installation requirements before selecting stock.',
    cta: 'Check palm availability', purpose: 'Date palm availability', image: 'assets/khairpur-date-palm-hero.webp', imageAlt: 'Date palm orchard in the warm light of Khairpur',
    facts: [['Aseel', 'Available from approximately 1–15 ft'], ['Qarbala', 'Available from approximately 1–10 ft'], ['Service', 'Supply and installation'], ['Origin', 'Khairpur Mirs, Sindh']],
    sections: [
      ['Aseel Date Palm', 'Khairpur’s best-known commercial date variety and a strong choice for orchard and landscape enquiries. Availability changes by height and season.', ['Multiple height bands', 'Farm and farmhouse use', 'Installation enquiry available']],
      ['Qarbala Date Palm', 'A regional date-palm option available in several young-to-established sizes. Exact stock and specification are confirmed before quotation.', ['Approximately 1–10 ft', 'Garden and farm enquiries', 'Direct nursery confirmation']],
      ['Mature Palms', 'Large palms require careful access, lifting, transportation and planting assessment. We quote these projects after reviewing location and site conditions.', ['Site-access review', 'Handling and delivery planning', 'Professional installation']],
    ],
  },
  {
    slug: 'aseel-date-palm', eyebrow: 'Khairpur’s signature variety', title: 'Aseel date palms, selected at the source.',
    description: 'Enquire about authentic Aseel date palm plants in multiple heights from Khairpur, with delivery and installation options.',
    intro: 'Aseel is deeply associated with Khairpur’s date-growing identity. Buyers can enquire about plants from approximately 1 ft through 15 ft, subject to current nursery stock.',
    cta: 'Enquire about Aseel', purpose: 'Aseel Date Palm', image: 'assets/khairpur-date-palm-hero.webp', imageAlt: 'Healthy date palms growing in a sunlit orchard',
    facts: [['Height range', 'Approximately 1–15 ft'], ['Best for', 'Farms, orchards and landscapes'], ['Quote basis', 'Height, quantity and destination'], ['Support', 'Supply and installation']],
    sections: [
      ['Who is it for?', 'Aseel suits agricultural buyers, farmhouses and landscape projects seeking a date palm with authentic Khairpur provenance.', ['Orchard enquiries', 'Statement landscape planting', 'Bulk and individual orders']],
      ['What affects the quotation?', 'Palm height alone is not enough. Quantity, access, destination and installation scope materially affect handling and transport.', ['Required quantity', 'Delivery city and access', 'Supply-only or installation']],
      ['Before you order', 'Ask for current stock imagery and confirm how the quoted height is measured. Fruiting, gender and age must be confirmed for the specific plant where applicable.', ['Current-stock confirmation', 'Specification confirmation', 'Site information']],
    ],
  },
  {
    slug: 'qarbala-date-palm', eyebrow: 'Regional palm selection', title: 'Qarbala palms for farms and gardens.',
    description: 'Qarbala date palm enquiries from Khairpur with multiple height options, delivery assessment and planting support.',
    intro: 'Qarbala palms are listed by the nursery from approximately 1 ft to 10 ft. Current availability is confirmed directly before quotation.',
    cta: 'Enquire about Qarbala', purpose: 'Qarbala Date Palm', image: 'assets/khairpur-date-palm-hero.webp', imageAlt: 'Established date palm trees in an agricultural landscape',
    facts: [['Height range', 'Approximately 1–10 ft'], ['Availability', 'Confirmed before quotation'], ['Use cases', 'Farm and garden enquiries'], ['Support', 'Delivery and installation assessment']],
    sections: [
      ['Choose by outcome', 'The right size depends on whether the objective is young establishment, orchard planting or faster visual impact.', ['Young planting stock', 'Established garden palms', 'Project quantities']],
      ['Plan delivery early', 'Larger palms need appropriate vehicle access, unloading space and a prepared planting location.', ['Destination review', 'Access assessment', 'Installation scope']],
      ['Get a useful quotation', 'Send city, quantity, required height and intended use in the first message to reduce delays and avoid inaccurate estimates.', ['City', 'Quantity and height', 'Purpose and timeline']],
    ],
  },
  {
    slug: 'palm-supply-delivery', eyebrow: 'From nursery to destination', title: 'Palm supply and delivery, planned properly.',
    description: 'Date palm supply and delivery enquiries from Khairpur for homes, farms and commercial landscape projects across Pakistan.',
    intro: 'A reliable delivery plan starts with the correct palm specification, quantity, destination and site-access information—not a generic transport estimate.',
    cta: 'Request delivery assessment', purpose: 'Palm supply and delivery', image: 'assets/real-palm-installation.webp', imageAlt: 'Mature date palm being handled by the Khairpur field team', imageAuthentic: true,
    facts: [['Stock', 'Confirmed at enquiry stage'], ['Delivery quote', 'Based on size, quantity and city'], ['Collection', 'Roadside collection listed'], ['Origin', 'Khairpur Mirs']],
    sections: [
      ['Supply confirmation', 'Current stock, variety and height should be confirmed before transport is planned.', ['Current imagery', 'Variety and quantity', 'Height specification']],
      ['Transport planning', 'Palm size and root preparation influence the appropriate vehicle and handling process.', ['Route and distance', 'Loading requirements', 'Safe support and protection']],
      ['Destination readiness', 'Access, unloading area and planting preparation should be reviewed before dispatch.', ['Vehicle access', 'Unloading space', 'Prepared planting area']],
    ],
  },
  {
    slug: 'palm-installation', eyebrow: 'Verified field capability', title: 'Professional mature-palm installation.',
    description: 'Machinery-assisted date palm installation and relocation enquiries backed by authentic field-work evidence.',
    intro: 'The Facebook archive contains authentic evidence of machinery-assisted mature-palm positioning and installation. Every new site still requires its own assessment.',
    cta: 'Discuss an installation', purpose: 'Professional palm installation', image: 'assets/real-palm-installation.webp', imageAlt: 'Machinery-assisted mature date palm installation by the company field team', imageAuthentic: true,
    facts: [['Evidence', 'Authentic company field media'], ['Method', 'Project-specific assessment'], ['Suitable for', 'Mature and large palms'], ['Quote needs', 'Location, access, size and quantity']],
    sections: [
      ['Why assessment matters', 'Large palms cannot be quoted responsibly from height alone. Ground conditions, access and equipment requirements change the plan.', ['Site photographs', 'Access measurements', 'Palm size and quantity']],
      ['What the service covers', 'Final scope is confirmed in the quotation and may include handling, transportation, positioning and planting.', ['Lifting plan', 'Placement coordination', 'Planting scope']],
      ['After installation', 'Watering and establishment guidance should be agreed for the specific project. No survival guarantee is implied unless written into the quotation.', ['Initial care instructions', 'Clear responsibility split', 'Written terms']],
    ],
  },
  {
    slug: 'date-products', eyebrow: 'From Khairpur’s date country', title: 'Aseel dates in more useful forms.',
    description: 'Fresh Aseel dates, dry dates, date paste, syrup and powder enquiries for retail and wholesale buyers.',
    intro: 'The public Facebook catalogue presents fresh Aseel dates and value-added date products for individual, food-service and commercial enquiries.',
    cta: 'Request product availability', purpose: 'Date products', image: 'assets/date-products-hero.webp', imageAlt: 'Aseel dates presented with date syrup, paste and powder',
    facts: [['Fresh fruit', 'Seasonal Aseel date enquiries'], ['Traditional', 'Dry dates / chuhara'], ['Ingredients', 'Date paste and syrup'], ['Format', 'Date powder enquiries']],
    sections: [
      ['Fresh Aseel Dates', 'Promoted as hand-picked, premium-quality Khairpur dates. Availability, grade and packaging must be confirmed for the current season.', ['Seasonal availability', 'Retail and bulk enquiry', 'Packaging confirmation']],
      ['Dry Dates / Chuhara', 'A traditional shelf-stable format for consumer and wholesale enquiries.', ['Grade confirmation', 'Pack-size enquiry', 'Bulk quantity enquiry']],
      ['Paste, Syrup and Powder', 'Formats relevant to bakeries, bars, food producers and buyers seeking date-based sweetening ingredients.', ['Food-business use cases', 'MOQ and pack size required', 'Shelf-life confirmation required']],
    ],
  },
  {
    slug: 'wholesale-export', eyebrow: 'Commercial enquiries', title: 'A clearer path for wholesale buyers.',
    description: 'Structured wholesale and export enquiries for Khairpur date products and seasonal Pakistani fruit shipments.',
    intro: 'Commercial buyers need product specification, volume, packaging, destination and documentation—not a generic retail message. This page captures those details first.',
    cta: 'Start wholesale enquiry', purpose: 'Wholesale or export enquiry', image: 'assets/date-export-hero.webp', imageAlt: 'Premium dates prepared in cartons and food-safe pouches for wholesale supply',
    facts: [['Products', 'Dates and value-added formats'], ['Buyer type', 'Retailers and food businesses'], ['Quote basis', 'Product, volume and destination'], ['Seasonal', 'Mango campaigns appear on Facebook']],
    sections: [
      ['For retailers', 'Request product type, grade, pack size and order quantity. Current availability is confirmed directly.', ['Retail packaging enquiry', 'Bulk carton enquiry', 'Destination details']],
      ['For food businesses', 'Date paste, syrup and powder may suit bakery or production use. Specifications and documentation require confirmation.', ['Required format', 'Monthly or one-off volume', 'Food-use requirements']],
      ['For export enquiries', 'Facebook has promoted international seasonal shipments, but destination coverage and export terms must be reconfirmed for every campaign.', ['Country and city', 'Required quantity', 'Timeline and documentation']],
    ],
  },
  {
    slug: 'projects', eyebrow: 'Evidence over claims', title: 'Real work from the field.',
    description: 'Verified project evidence from Khairpur Date Palm & Nursery, beginning with mature palm installation.',
    intro: 'Only projects supported by authentic company media belong here. Stock imagery and AI-generated scenes are not presented as completed work.',
    cta: 'Discuss your project', purpose: 'Project enquiry', image: 'assets/real-palm-installation.webp', imageAlt: 'Authentic machinery-assisted date palm installation project', imageAuthentic: true,
    facts: [['Verified category', 'Mature palm installation'], ['Evidence source', 'Company Facebook archive'], ['Media status', 'Authentic field photograph'], ['Expansion', 'More case studies require owner data']],
    sections: [
      ['Mature Palm Field Installation', 'Authentic media shows a large palm being positioned with machinery while the field team prepares the planting area.', ['Machinery-assisted handling', 'On-site crew', 'Prepared installation area']],
      ['What is not yet documented', 'The public post does not specify location, client, date, quantity, project challenge or follow-up result.', ['Location needed', 'Scope and timeline needed', 'Aftercare result needed']],
      ['Case-study standard', 'Future projects should include before, during and after imagery plus written scope, measurable outcome and customer permission.', ['Before/after set', 'Client-approved description', 'Related service and CTA']],
    ],
    gallery: [
      ['assets/real-palm-installation.webp', 'Mature palm installation', 'Machinery-assisted positioning and field planting', 720, 960],
      ['assets/facebook/mango-harvest.jpg', 'Seasonal harvest', 'Authentic farm handling from the Facebook archive', 206, 206],
      ['assets/facebook/mango-sorting.jpg', 'Farm sorting', 'Fruit selection during seasonal activity', 206, 206],
      ['assets/facebook/mango-packing.jpg', 'Packing activity', 'Fruit prepared for onward delivery', 206, 206],
      ['assets/facebook/product-range.jpg', 'Product communication', 'Public Facebook product-range artwork', 206, 206],
    ],
  },
  {
    slug: 'about', eyebrow: 'Rooted in Khairpur', title: 'Local knowledge. Direct responsibility.',
    description: 'Learn what is publicly verified about Khairpur Date Palm & Nursery and the standards guiding its website content.',
    intro: 'Khairpur Date Palm & Nursery operates from Khairpur Mirs and publicly positions itself around palm supply, installation and date-related products.',
    cta: 'Speak with the nursery', purpose: 'General business enquiry', image: 'assets/real-palm-installation.webp', imageAlt: 'Khairpur Date Palm and Nursery team carrying out a mature palm installation', imageAuthentic: true,
    facts: [['Community', 'Approximately 29K Facebook followers'], ['Category', 'Landscape company'], ['Hours', 'Always open on Facebook'], ['Collection', 'Roadside collection listed']],
    sections: [
      ['What we can verify', 'The company publicly lists Khairpur Mirs, a direct mobile number, email, palm supply and installation.', ['Public contact details', 'Palm and date-product media', 'Authentic installation evidence']],
      ['What we will not invent', 'Years in business, team biographies, certifications and project totals will be published only after owner verification.', ['No fabricated statistics', 'No invented testimonials', 'No stock images labelled as projects']],
      ['A better digital standard', 'The website organizes scattered Facebook content into product, service, project and enquiry journeys designed to answer buyer questions.', ['Clear product paths', 'Evidence-backed trust', 'Structured WhatsApp leads']],
    ],
  },
  {
    slug: 'contact', eyebrow: 'Direct nursery contact', title: 'Start with the details that matter.',
    description: 'Contact Khairpur Date Palm & Nursery for plant, installation, date-product, wholesale and export enquiries.',
    intro: 'A complete first message helps the nursery respond faster and more accurately. Share product, quantity, city, preferred size or pack format and timeline.',
    cta: 'Open structured WhatsApp enquiry', purpose: 'General enquiry', image: 'assets/khairpur-date-palm-hero.webp', imageAlt: 'Khairpur date palm orchard at golden hour',
    facts: [['Mobile / WhatsApp', '0302 3111589'], ['Email', 'kanhar4u@yahoo.com'], ['Location', 'Khairpur Mirs, Pakistan'], ['Hours', 'Always open on Facebook']],
    sections: [
      ['Palm enquiry checklist', 'Include variety, required height, quantity, delivery city and whether installation is required.', ['Variety', 'Height and quantity', 'City and site access']],
      ['Date-product checklist', 'Include product format, retail or wholesale status, quantity, packaging requirement and destination.', ['Product and volume', 'Pack format', 'Destination and timing']],
      ['Response quality', 'Clear inputs reduce repeated questions and make the first quotation materially more useful.', ['One structured message', 'Faster qualification', 'Fewer surprises']],
    ],
  },
];
